[project]
name = "sniplink"
version = "0.1.0"
description = "This is a solution to the URL shortener project on roadmap.sh : https://roadmap.sh/projects/url-shortening-service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
