# Generated by Django 5.2.6 on 2025-09-21 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The original long URL to be shortened",
                        max_length=2048,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        help_text="The unique short code for the URL",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this short URL has been accessed",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shortened URL",
                "verbose_name_plural": "Shortened URLs",
                "ordering": ["-created_at"],
            },
        ),
    ]
